# Generated by Django 4.1.5 on 2023-01-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('value', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('nature', models.CharField(max_length=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='stores.store')),
            ],
        ),
    ]
