# Generated by Django 4.1.5 on 2023-01-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnab',
            name='type',
            field=models.CharField(max_length=22),
        ),
    ]
